# Generated by Django 3.0.1 on 2020-01-31 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('experience', models.CharField(choices=[('N', 'Novice'), ('E', 'Experienced')], max_length=1)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ELeagueUser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='archer',
            constraint=models.UniqueConstraint(fields=('university', 'first_name', 'last_name', 'sex', 'created_at'), name='unique_archer'),
        ),
    ]
