# Generated by Django 3.0.1 on 2020-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('M', 'Metric'), ('I', 'Imperial')], max_length=1)),
                ('season', models.CharField(choices=[('I', 'Indoor'), ('O', 'Outdoor')], max_length=1)),
                ('num_arrows', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'season'), name='unique_round'),
        ),
    ]
