# Generated by Django 3.0.1 on 2020-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200131_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
