# Generated by Django 3.0.1 on 2020-01-31 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import league.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_round_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('divisions', league.models.DivisionsField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Round')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('golds', models.IntegerField()),
                ('xs', models.IntegerField(blank=True, null=True)),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Archer')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leagueentry',
            constraint=models.UniqueConstraint(fields=('league', 'archer'), name='unique_archer_entry'),
        ),
        migrations.AddConstraint(
            model_name='leagueentry',
            constraint=models.CheckConstraint(check=models.Q(score__gte=0), name='score_positive'),
        ),
        migrations.AddConstraint(
            model_name='leagueentry',
            constraint=models.CheckConstraint(check=models.Q(hits__gte=0), name='hits_positive'),
        ),
        migrations.AddConstraint(
            model_name='leagueentry',
            constraint=models.CheckConstraint(check=models.Q(golds__gte=0), name='golds_positive'),
        ),
    ]
