# Generated by Django 3.0.1 on 2020-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20200131_1358'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='archer',
            name='unique_archer',
        ),
        migrations.AddField(
            model_name='archer',
            name='middle_names',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='archer',
            constraint=models.UniqueConstraint(fields=('university', 'first_name', 'middle_names', 'last_name', 'sex', 'created_at'), name='unique_archer'),
        ),
    ]
