# Generated by Django 3.0.1 on 2020-02-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20200207_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('max_teams', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='divisions',
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.CheckConstraint(check=models.Q(max_teams__gt=0), name='There must be at least 1 team per division'),
        ),
        migrations.AddField(
            model_name='league',
            name='divisions',
            field=models.ManyToManyField(related_name='divisions', to='league.Division'),
        ),
    ]
