# Generated by Django 3.0.1 on 2020-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20200207_1315'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leagueentry',
            name='score_positive',
        ),
        migrations.RemoveConstraint(
            model_name='leagueentry',
            name='hits_positive',
        ),
        migrations.RemoveConstraint(
            model_name='leagueentry',
            name='golds_positive',
        ),
        migrations.AddField(
            model_name='league',
            name='process_at',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='max_teams',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leagueentry',
            name='golds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leagueentry',
            name='hits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leagueentry',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='num_arrows',
            field=models.PositiveIntegerField(),
        ),
    ]
