# Generated by Django 3.0.1 on 2020-03-21 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20200207_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='splits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True), default=list, help_text='The submission dates for each split', size=None),
        ),
    ]
