# Generated by Django 3.0.1 on 2020-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_auto_20200321_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(help_text='The name of this division e.g.: "Division 1"', max_length=64),
        ),
    ]
