# Generated by Django 3.0.1 on 2020-03-21 13:32

import django.core.validators
from django.db import migrations, models
import league.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20200321_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='max_teams',
            field=models.IntegerField(default=-1, help_text='The maximum number of teams from one university allowed into this division. Use -1 for unlimited teams.', validators=[league.models.non_zero_validator, django.core.validators.MinValueValidator(limit_value=-1)]),
        ),
    ]
