# Generated by Django 3.0.1 on 2020-03-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20200321_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='process_at',
        ),
    ]
