# Generated by Django 3.0.1 on 2020-03-21 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_remove_league_process_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='process_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
