# Generated by Django 3.0.1 on 2020-03-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_league_process_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Then name of this split e.g.: "December/January".', max_length=200)),
                ('split_ends', models.DateField(help_text='The last day that will be valid for scores in this split. This date is inclusive.')),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='splits',
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(help_text='The name of this division e.g.: "Division 1".', max_length=64),
        ),
    ]
