# Generated by Django 3.0.1 on 2020-05-24 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20200426_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueentry',
            name='shot_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
