# Generated by Django 3.0.1 on 2020-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_leagueentry_shot_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='process_at',
            field=models.DurationField(help_text='The amount of time after a split closes before the scores are processed and the league table(s) are generated for the split.'),
        ),
    ]
