# Generated by Django 3.0.1 on 2020-05-26 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_auto_20200526_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='process_at',
            field=models.DurationField(default=datetime.timedelta(days=5), help_text='The amount of time after a split closes before the scores are processed and the league table(s) are generated for the split.'),
        ),
    ]
